### PR TITLE
Company register page

### PR DESCRIPTION
**Pull request by Peanutt47**
## This pull request creates the Company Registration page, which includes the following components:

- **ProfileImageForm.tsx**: Used for uploading a profile image.
- **CompanyRegisterForm.tsx**: Contains the registration form.
- **BannerImageForm.tsx**: Used for uploading a banner image.

### CODE REVIEW

**Review by xNatthapol — CHANGES_REQUESTED** [review]
Add a guidance message below the company logo upload.

**Review by xNatthapol — APPROVED** [review]
Thank you for adding the guidance message. I tested it, and it worked properly for me.

**Review by SmileyFaceZ — CHANGES_REQUESTED** [review]
Missing title on the top form.

**Review by SmileyFaceZ — CHANGES_REQUESTED** [review]
Missing an upload for the company background image and a short description warning in the **'Documentation'**.

**Review by xNatthapol — CHANGES_REQUESTED** [review]
Based on the new design, I tested the banner upload, and when I upload the banner, it appears at the profile image.

**Review by SmileyFaceZ — CHANGES_REQUESTED** [review]
Yeah!, when I upload the banner, it appears at the profile image.

**Review by SmileyFaceZ — APPROVED** [review]
Everything work well 👍.

**Review by xNatthapol — APPROVED** [review]
I tested the logo and banner upload, and it now works well for me.

**Pull request merged**
